jwt:
  secret-key: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey

oauth:
  kakao:
    client-secret: qxUdblnJfhxjWq1WRpdKwaKXzAlwUCxn
    client-id: 5ee390ed02f07429bd0ae6ccd98f0559
    redirect:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
#  naver:
#    secret: W_2DmcLfYU
#    client-id: Y2i4SlApP7A1KZsUoott
#    url:
#      auth: https://nid.naver.com
#      api: https://openapi.naver.com
spring:
  redis:
    host: 43.200.182.242
    port: 6379
    password: quoridor